### ISSUE TITLE
Incorrect Release Tag for version 1.0.4

### ISSUE THREAD

**Issue by DingDean** [hertz-contrib/reverseproxy#17]
**Describe the bug**

This technically is not a bug but a CD fault?
The version released after v.1.0.3 is tagged with `v0.1.4`，which is really confusing and it's not get installed by default if not specifying target version when installing.

**To Reproduce**
Please refer to the release page: https://github.com/hertz-contrib/reverseproxy/releases

**Expected behavior**

The latest tag should be v1.0.4?

**Screenshots**

<img width="979" alt="截屏2023-12-17 21 04 09" src="https://github.com/hertz-contrib/reverseproxy/assets/11747908/f8e2119c-efa4-4be5-8e5e-855edecc0f69">

**Comment by li-jin-gou** [comment]
thanks



---Original---
From: "Ke ***@***.***&gt;
Date: Sun, Dec 17, 2023 21:12 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [hertz-contrib/reverseproxy] Incorrect Release Tag for version 1.0.4(Issue #17)




 
Describe the bug
 
This technically is not a bug but a CD fault?
 The version released after v.1.0.3 is tagged with v0.1.4，which is really confusing and it's not get installed by default if not specifying target version when installing.
 
To Reproduce
 Please refer to the release page: https://github.com/hertz-contrib/reverseproxy/releases
 
Expected behavior
 
The latest tag should be v1.0.4?
 
Screenshots
 2023-12-17.21.04.09.png (view on web)
